import { ChevronDown, ChevronUp, GripVertical, Plus, Trash2 } from 'lucide-react'
import type { EducationItem, ExperienceItem, ProjectItem, Resume } from '../../types/resume'
import { emptyEducation, emptyExperience, emptyProject, moveAt } from './editorUtils'
import { BulletEditor, Field, Section, SimpleList, TextareaField } from './EditorPrimitives'

type SectionEditorProps = { resume: Resume; onChange: (resume: Resume) => void }
const updateList = <K extends keyof Resume>(resume: Resume, onChange: (resume: Resume) => void, key: K, value: Resume[K]) => onChange({ ...resume, [key]: value })
const updateItem = <T extends { id: string }>(items: T[], id: string, patch: Partial<T>) => items.map((item) => item.id === id ? { ...item, ...patch } : item)

export function ProfileSection({ resume, onChange }: SectionEditorProps) {
  const updateProfile = (key: keyof Resume['profile'], value: string) => onChange({ ...resume, profile: { ...resume.profile, [key]: value } })
  return <Section title="个人信息" description="让招聘者快速了解你"><div className="field-grid"><Field label="姓名" value={resume.profile.fullName} placeholder="例如：张三" onChange={(value) => updateProfile('fullName', value)} /><Field label="职位" value={resume.profile.jobTitle} placeholder="例如：产品经理" onChange={(value) => updateProfile('jobTitle', value)} /><Field label="邮箱" value={resume.profile.email} placeholder="name@example.com" type="email" onChange={(value) => updateProfile('email', value)} /><Field label="电话" value={resume.profile.phone} placeholder="+86 138 0000 0000" onChange={(value) => updateProfile('phone', value)} /><Field label="所在地" value={resume.profile.location} placeholder="城市，国家" onChange={(value) => updateProfile('location', value)} /><Field label="个人网站" value={resume.profile.website} placeholder="yourwebsite.com" type="url" onChange={(value) => updateProfile('website', value)} /></div></Section>
}

export function SummarySection({ resume, onChange }: SectionEditorProps) {
  return <Section title="个人简介" description="用几句话概括你的优势" defaultOpen={Boolean(resume.summary)}><TextareaField label="简介内容" value={resume.summary} placeholder="介绍你的经验、专长和职业方向……" onChange={(value) => updateList(resume, onChange, 'summary', value)} /></Section>
}

export function ExperienceSection({ resume, onChange }: SectionEditorProps) {
  const update = (items: ExperienceItem[]) => updateList(resume, onChange, 'experience', items)
  return <Section title="工作经历" description={`${resume.experience.length} 段经历`}><div className="repeat-list">{resume.experience.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} aria-hidden="true" />经历 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update(moveAt(resume.experience, index, -1))} aria-label="上移经历"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.experience.length - 1} onClick={() => update(moveAt(resume.experience, index, 1))} aria-label="下移经历"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update(resume.experience.filter((entry) => entry.id !== item.id))} aria-label="删除经历"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="公司" value={item.company} placeholder="公司名称" onChange={(value) => update(updateItem(resume.experience, item.id, { company: value }))} /><Field label="职位" value={item.role} placeholder="职位名称" onChange={(value) => update(updateItem(resume.experience, item.id, { role: value }))} /><Field label="所在地" value={item.location} placeholder="城市" onChange={(value) => update(updateItem(resume.experience, item.id, { location: value }))} /><div className="field-row"><Field label="开始时间" value={item.startDate} type="month" onChange={(value) => update(updateItem(resume.experience, item.id, { startDate: value }))} />{!item.current && <Field label="结束时间" value={item.endDate} type="month" onChange={(value) => update(updateItem(resume.experience, item.id, { endDate: value }))} />}</div></div><label className="checkbox-field"><input type="checkbox" checked={item.current} onChange={(event) => update(updateItem(resume.experience, item.id, { current: event.target.checked, endDate: event.target.checked ? '' : item.endDate }))} /><span>我目前在这里工作</span></label><BulletEditor bullets={item.bullets} onChange={(bullets) => update(updateItem(resume.experience, item.id, { bullets }))} /></div>)}</div><button className="add-button" type="button" onClick={() => update([...resume.experience, emptyExperience()])}><Plus size={16} />添加工作经历</button></Section>
}

export function EducationSection({ resume, onChange }: SectionEditorProps) {
  const update = (items: EducationItem[]) => updateList(resume, onChange, 'education', items)
  return <Section title="教育经历" description={`${resume.education.length} 段经历`}><div className="repeat-list">{resume.education.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} aria-hidden="true" />教育经历 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update(moveAt(resume.education, index, -1))} aria-label="上移教育经历"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.education.length - 1} onClick={() => update(moveAt(resume.education, index, 1))} aria-label="下移教育经历"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update(resume.education.filter((entry) => entry.id !== item.id))} aria-label="删除教育经历"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="学校" value={item.school} placeholder="学校名称" onChange={(value) => update(updateItem(resume.education, item.id, { school: value }))} /><Field label="学位" value={item.degree} placeholder="例如：本科" onChange={(value) => update(updateItem(resume.education, item.id, { degree: value }))} /><Field label="专业" value={item.field} placeholder="专业名称" onChange={(value) => update(updateItem(resume.education, item.id, { field: value }))} /><div className="field-row"><Field label="开始时间" value={item.startDate} placeholder="2018" onChange={(value) => update(updateItem(resume.education, item.id, { startDate: value }))} /><Field label="结束时间" value={item.endDate} placeholder="2022" onChange={(value) => update(updateItem(resume.education, item.id, { endDate: value }))} /></div></div></div>)}</div><button className="add-button" type="button" onClick={() => update([...resume.education, emptyEducation()])}><Plus size={16} />添加教育经历</button></Section>
}

export function SkillsSection({ resume, onChange }: SectionEditorProps) {
  return <Section title="技能" description="用关键词突出你的能力"><SimpleList values={resume.skills} label="技能" placeholder="例如：项目管理" emptyText="还没有添加技能" onChange={(values) => updateList(resume, onChange, 'skills', values)} /></Section>
}

export function ProjectsSection({ resume, onChange }: SectionEditorProps) {
  const update = (items: ProjectItem[]) => updateList(resume, onChange, 'projects', items)
  return <Section title="项目经历" description={`${resume.projects.length} 个项目`}><div className="repeat-list">{resume.projects.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} aria-hidden="true" />项目 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update(moveAt(resume.projects, index, -1))} aria-label="上移项目"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.projects.length - 1} onClick={() => update(moveAt(resume.projects, index, 1))} aria-label="下移项目"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update(resume.projects.filter((entry) => entry.id !== item.id))} aria-label="删除项目"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="项目名称" value={item.name} placeholder="项目名称" onChange={(value) => update(updateItem(resume.projects, item.id, { name: value }))} /><Field label="项目链接" value={item.url} placeholder="yourproject.com" type="url" onChange={(value) => update(updateItem(resume.projects, item.id, { url: value }))} /><TextareaField label="项目描述" value={item.description} placeholder="简述项目背景和你的贡献" onChange={(value) => update(updateItem(resume.projects, item.id, { description: value }))} /></div><BulletEditor bullets={item.bullets} onChange={(bullets) => update(updateItem(resume.projects, item.id, { bullets }))} /></div>)}</div><button className="add-button" type="button" onClick={() => update([...resume.projects, emptyProject()])}><Plus size={16} />添加项目经历</button></Section>
}

export function LanguagesSection({ resume, onChange }: SectionEditorProps) {
  return <Section title="语言" description="你掌握的语言及熟练度"><SimpleList values={resume.languages} label="语言" placeholder="例如：英语（熟练）" emptyText="还没有添加语言" onChange={(values) => updateList(resume, onChange, 'languages', values)} /></Section>
}
