import type { Resume } from '../../types/resume'
import type { ResumeContent } from '../../utils/resume'
import { cleanUrl, formatResumePeriod, toSafeExternalUrl } from '../../utils/resume'
import { EditableText, text } from './PreviewText'

type ResumeSectionsProps = {
  resume: Resume
  content: ResumeContent
  editing: boolean
  isVisible: (section: keyof Resume['layout']['sectionTitles']) => boolean
  sectionTitle: (section: keyof Resume['layout']['sectionTitles']) => string
  editExperience: (id: string, key: keyof Resume['experience'][number], value: string) => void
  editBullet: (id: string, sourceIndex: number, value: string) => void
  editEducation: (id: string, key: keyof Resume['education'][number], value: string) => void
  editProject: (id: string, key: keyof Resume['projects'][number], value: string) => void
  editProjectBullet: (id: string, sourceIndex: number, value: string) => void
  editList: (key: 'skills' | 'languages', sourceIndex: number, value: string) => void
  editSummary: (value: string) => void
}

export default function ResumeSections({ resume, content, editing, isVisible, sectionTitle, editExperience, editBullet, editEducation, editProject, editProjectBullet, editList, editSummary }: ResumeSectionsProps) {
  const hasResumeContent = content.profile.fullName.trim() || content.profile.jobTitle.trim() || [content.profile.email, content.profile.phone, content.profile.location, content.profile.website].some((value) => value.trim()) || content.summary.trim() || content.experience.length || content.education.length || content.skills.length || content.projects.length || content.languages.length

  return <>
    {!hasResumeContent && <div className="resume-empty">编辑内容后，预览会即时显示在这里</div>}
    {isVisible('summary') && content.summary.trim() && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('summary') + 1 }}><h2>{sectionTitle('summary')}</h2>{text(content.summary, editing, editSummary, 'p', '个人简介', undefined, undefined, true)}</section>}
    {isVisible('experience') && content.experience.length > 0 && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('experience') + 1 }}><h2>{sectionTitle('experience')}</h2>{content.experience.map((item, index) => <article className="resume-entry" key={item.id}><div className="entry-heading"><div><h3>{editing || item.role.trim() ? text(item.role, editing, (value) => editExperience(item.id, 'role', value), 'span', `经历 ${index + 1} · 职位`, '职位名称') : text(item.company, editing, (value) => editExperience(item.id, 'company', value), 'span', `经历 ${index + 1} · 公司`, '公司名称')}</h3>{[item.company, item.role, item.location].some((value) => value.trim()) && <p>{item.company.trim() && text(item.company, editing, (value) => editExperience(item.id, 'company', value), 'span', `经历 ${index + 1} · 公司`, '公司名称')}{item.company.trim() && item.role.trim() && ' · '}{item.location.trim() && text(item.location, editing, (value) => editExperience(item.id, 'location', value), 'span', `经历 ${index + 1} · 所在地`, '所在地')}</p>}</div><time>{editing ? <><EditableText value={item.startDate} onChange={(value) => editExperience(item.id, 'startDate', value)} ariaLabel={`经历 ${index + 1} · 开始时间`} placeholder="开始时间" />{(item.startDate || item.endDate || item.current) && ' — '}{item.current ? '至今' : <EditableText value={item.endDate} onChange={(value) => editExperience(item.id, 'endDate', value)} ariaLabel={`经历 ${index + 1} · 结束时间`} placeholder="结束时间" />}</> : formatResumePeriod(item.startDate, item.endDate, item.current)}</time></div>{item.visibleBullets.length > 0 && <ul>{item.visibleBullets.map((bullet, bulletIndex) => <li key={`${item.id}-bullet-${bullet.sourceIndex}`}>{editing ? <EditableText value={bullet.value} onChange={(value) => editBullet(item.id, bullet.sourceIndex, value)} ariaLabel={`经历 ${index + 1} · 工作成果 ${bulletIndex + 1}`} /> : bullet.value}</li>)}</ul>}</article>)}</section>}
    {isVisible('education') && content.education.length > 0 && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('education') + 1 }}><h2>{sectionTitle('education')}</h2>{content.education.map((item, index) => <article className="resume-entry" key={item.id}><div className="entry-heading"><div><h3>{editing || item.school.trim() ? text(item.school, editing, (value) => editEducation(item.id, 'school', value), 'span', `教育经历 ${index + 1} · 学校`, '学校名称') : text(item.degree, editing, (value) => editEducation(item.id, 'degree', value), 'span', `教育经历 ${index + 1} · 学位`, '学位')}</h3>{[item.degree, item.field].some((value) => value.trim()) && <p>{item.degree.trim() && text(item.degree, editing, (value) => editEducation(item.id, 'degree', value), 'span', `教育经历 ${index + 1} · 学位`, '学位')}{item.degree.trim() && item.field.trim() && ' · '}{item.field.trim() && text(item.field, editing, (value) => editEducation(item.id, 'field', value), 'span', `教育经历 ${index + 1} · 专业`, '专业')}</p>}</div><time>{editing ? <><EditableText value={item.startDate} onChange={(value) => editEducation(item.id, 'startDate', value)} ariaLabel={`教育经历 ${index + 1} · 开始时间`} />{(item.startDate || item.endDate) && ' — '}<EditableText value={item.endDate} onChange={(value) => editEducation(item.id, 'endDate', value)} ariaLabel={`教育经历 ${index + 1} · 结束时间`} /></> : formatResumePeriod(item.startDate, item.endDate, false)}</time></div></article>)}</section>}
    {isVisible('skills') && content.skills.length > 0 && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('skills') + 1 }}><h2>{sectionTitle('skills')}</h2><div className="resume-tags">{content.skills.map((skill, index) => <span key={`skill-${skill.sourceIndex}`}>{editing ? <EditableText value={skill.value} onChange={(value) => editList('skills', skill.sourceIndex, value)} as="span" ariaLabel={`技能 ${index + 1}`} /> : skill.value}</span>)}</div></section>}
    {isVisible('projects') && content.projects.length > 0 && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('projects') + 1 }}><h2>{sectionTitle('projects')}</h2>{content.projects.map((item, index) => { const projectUrl = toSafeExternalUrl(item.url); return <article className="resume-entry" key={item.id}><div className="entry-heading"><div><h3>{editing || item.name.trim() ? text(item.name, editing, (value) => editProject(item.id, 'name', value), 'span', `项目经历 ${index + 1} · 项目名称`, '项目名称') : item.url ? cleanUrl(item.url) : ''}</h3>{item.url && (editing ? <EditableText value={cleanUrl(item.url)} onChange={(value) => editProject(item.id, 'url', value)} as="span" className="entry-url" ariaLabel={`项目经历 ${index + 1} · 项目链接`} /> : projectUrl ? <a className="entry-url" href={projectUrl} target="_blank" rel="noreferrer">{cleanUrl(item.url)}</a> : <p className="entry-url">{cleanUrl(item.url)}</p>)}</div></div>{item.description.trim() && text(item.description, editing, (value) => editProject(item.id, 'description', value), 'p', `项目经历 ${index + 1} · 项目描述`, undefined, undefined, true)}{item.visibleBullets.length > 0 && <ul>{item.visibleBullets.map((bullet, bulletIndex) => <li key={`${item.id}-bullet-${bullet.sourceIndex}`}>{editing ? <EditableText value={bullet.value} onChange={(value) => editProjectBullet(item.id, bullet.sourceIndex, value)} ariaLabel={`项目经历 ${index + 1} · 项目成果 ${bulletIndex + 1}`} /> : bullet.value}</li>)}</ul>}</article> })}</section>}
    {isVisible('languages') && content.languages.length > 0 && <section className="resume-section" style={{ order: resume.layout.sectionOrder.indexOf('languages') + 1 }}><h2>{sectionTitle('languages')}</h2><p>{content.languages.map((language, index) => <span key={`language-${language.sourceIndex}`}>{editing ? <EditableText value={language.value} onChange={(value) => editList('languages', language.sourceIndex, value)} ariaLabel={`语言 ${index + 1}`} /> : language.value}{index < content.languages.length - 1 && ' · '}</span>)}</p></section>}
  </>
}
