import { useState } from 'react'
import { ChevronDown, ChevronUp, GripVertical, Plus, Trash2 } from 'lucide-react'
import type { EducationItem, ExperienceItem, ProjectItem, Resume } from '../types/resume'

type ResumeEditorProps = { resume: Resume; onChange: (resume: Resume) => void }
type SectionProps = { title: string; description?: string; defaultOpen?: boolean; children: React.ReactNode }

const Section = ({ title, description, defaultOpen = true, children }: SectionProps) => {
  const [open, setOpen] = useState(defaultOpen)
  return <section className="editor-section"><button className="section-toggle" type="button" onClick={() => setOpen(!open)} aria-expanded={open}><span><strong>{title}</strong>{description && <small>{description}</small>}</span>{open ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button>{open && <div className="section-body">{children}</div>}</section>
}

const Field = ({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) => <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>
const TextareaField = ({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) => <label className="field field-full"><span>{label}</span><textarea value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} rows={4} /></label>

const addAt = <T,>(items: T[], index: number, value: T) => [...items.slice(0, index), value, ...items.slice(index)]
const moveAt = <T,>(items: T[], index: number, direction: -1 | 1) => { const next = index + direction; if (next < 0 || next >= items.length) return items; const result = [...items]; [result[index], result[next]] = [result[next], result[index]]; return result }

const emptyExperience = (): ExperienceItem => ({ id: crypto.randomUUID(), company: '', role: '', location: '', startDate: '', endDate: '', current: false, bullets: [''] })
const emptyEducation = (): EducationItem => ({ id: crypto.randomUUID(), school: '', degree: '', field: '', startDate: '', endDate: '' })
const emptyProject = (): ProjectItem => ({ id: crypto.randomUUID(), name: '', description: '', url: '', bullets: [''] })

export default function ResumeEditor({ resume, onChange }: ResumeEditorProps) {
  const update = <K extends keyof Resume>(key: K, value: Resume[K]) => onChange({ ...resume, [key]: value })
  const updateProfile = (key: keyof Resume['profile'], value: string) => onChange({ ...resume, profile: { ...resume.profile, [key]: value } })

  return <div className="editor-sections">
    <Section title="个人信息" description="让招聘者快速了解你">
      <div className="field-grid"><Field label="姓名" value={resume.profile.fullName} placeholder="例如：张三" onChange={(value) => updateProfile('fullName', value)} /><Field label="职位" value={resume.profile.jobTitle} placeholder="例如：产品经理" onChange={(value) => updateProfile('jobTitle', value)} /><Field label="邮箱" value={resume.profile.email} placeholder="name@example.com" type="email" onChange={(value) => updateProfile('email', value)} /><Field label="电话" value={resume.profile.phone} placeholder="+86 138 0000 0000" onChange={(value) => updateProfile('phone', value)} /><Field label="所在地" value={resume.profile.location} placeholder="城市，国家" onChange={(value) => updateProfile('location', value)} /><Field label="个人网站" value={resume.profile.website} placeholder="yourwebsite.com" onChange={(value) => updateProfile('website', value)} /></div>
    </Section>

    <Section title="个人简介" description="用几句话概括你的优势" defaultOpen={Boolean(resume.summary)}><TextareaField label="简介内容" value={resume.summary} placeholder="介绍你的经验、专长和职业方向……" onChange={(value) => update('summary', value)} /></Section>

    <Section title="工作经历" description={`${resume.experience.length} 段经历`}>
      <div className="repeat-list">{resume.experience.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} />经历 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update('experience', moveAt(resume.experience, index, -1))} aria-label="上移经历" title="上移"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.experience.length - 1} onClick={() => update('experience', moveAt(resume.experience, index, 1))} aria-label="下移经历" title="下移"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update('experience', resume.experience.filter((entry) => entry.id !== item.id))} aria-label="删除经历" title="删除"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="公司" value={item.company} placeholder="公司名称" onChange={(value) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, company: value } : entry))} /><Field label="职位" value={item.role} placeholder="职位名称" onChange={(value) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, role: value } : entry))} /><Field label="所在地" value={item.location} placeholder="城市" onChange={(value) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, location: value } : entry))} /><div className="field-row"><Field label="开始时间" value={item.startDate} type="month" onChange={(value) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, startDate: value } : entry))} />{!item.current && <Field label="结束时间" value={item.endDate} type="month" onChange={(value) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, endDate: value } : entry))} />}</div></div><label className="checkbox-field"><input type="checkbox" checked={item.current} onChange={(event) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, current: event.target.checked, endDate: event.target.checked ? '' : entry.endDate } : entry))} /><span>我目前在这里工作</span></label><BulletEditor bullets={item.bullets} onChange={(bullets) => update('experience', resume.experience.map((entry) => entry.id === item.id ? { ...entry, bullets } : entry))} /></div>)}</div>
      <button className="add-button" type="button" onClick={() => update('experience', [...resume.experience, emptyExperience()])}><Plus size={16} />添加工作经历</button>
    </Section>

    <Section title="教育经历" description={`${resume.education.length} 段经历`}>
      <div className="repeat-list">{resume.education.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} />教育经历 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update('education', moveAt(resume.education, index, -1))} aria-label="上移教育经历" title="上移"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.education.length - 1} onClick={() => update('education', moveAt(resume.education, index, 1))} aria-label="下移教育经历" title="下移"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update('education', resume.education.filter((entry) => entry.id !== item.id))} aria-label="删除教育经历" title="删除"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="学校" value={item.school} placeholder="学校名称" onChange={(value) => update('education', resume.education.map((entry) => entry.id === item.id ? { ...entry, school: value } : entry))} /><Field label="学位" value={item.degree} placeholder="例如：本科" onChange={(value) => update('education', resume.education.map((entry) => entry.id === item.id ? { ...entry, degree: value } : entry))} /><Field label="专业" value={item.field} placeholder="专业名称" onChange={(value) => update('education', resume.education.map((entry) => entry.id === item.id ? { ...entry, field: value } : entry))} /><div className="field-row"><Field label="开始时间" value={item.startDate} placeholder="2018" onChange={(value) => update('education', resume.education.map((entry) => entry.id === item.id ? { ...entry, startDate: value } : entry))} /><Field label="结束时间" value={item.endDate} placeholder="2022" onChange={(value) => update('education', resume.education.map((entry) => entry.id === item.id ? { ...entry, endDate: value } : entry))} /></div></div></div>)}</div>
      <button className="add-button" type="button" onClick={() => update('education', [...resume.education, emptyEducation()])}><Plus size={16} />添加教育经历</button>
    </Section>

    <Section title="技能" description="用关键词突出你的能力"><SimpleList values={resume.skills} placeholder="例如：项目管理" emptyText="还没有添加技能" onChange={(values) => update('skills', values)} /></Section>

    <Section title="项目经历" description={`${resume.projects.length} 个项目`}>
      <div className="repeat-list">{resume.projects.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-card-heading"><span><GripVertical size={16} />项目 {index + 1}</span><div className="repeat-actions"><button className="icon-button" type="button" disabled={index === 0} onClick={() => update('projects', moveAt(resume.projects, index, -1))} aria-label="上移项目" title="上移"><ChevronUp size={15} /></button><button className="icon-button" type="button" disabled={index === resume.projects.length - 1} onClick={() => update('projects', moveAt(resume.projects, index, 1))} aria-label="下移项目" title="下移"><ChevronDown size={15} /></button><button className="icon-button danger-icon" type="button" onClick={() => update('projects', resume.projects.filter((entry) => entry.id !== item.id))} aria-label="删除项目" title="删除"><Trash2 size={15} /></button></div></div><div className="field-grid"><Field label="项目名称" value={item.name} placeholder="项目名称" onChange={(value) => update('projects', resume.projects.map((entry) => entry.id === item.id ? { ...entry, name: value } : entry))} /><Field label="项目链接" value={item.url} placeholder="yourproject.com" onChange={(value) => update('projects', resume.projects.map((entry) => entry.id === item.id ? { ...entry, url: value } : entry))} /><TextareaField label="项目描述" value={item.description} placeholder="简述项目背景和你的贡献" onChange={(value) => update('projects', resume.projects.map((entry) => entry.id === item.id ? { ...entry, description: value } : entry))} /></div><BulletEditor bullets={item.bullets} onChange={(bullets) => update('projects', resume.projects.map((entry) => entry.id === item.id ? { ...entry, bullets } : entry))} /></div>)}</div>
      <button className="add-button" type="button" onClick={() => update('projects', [...resume.projects, emptyProject()])}><Plus size={16} />添加项目经历</button>
    </Section>

    <Section title="语言" description="你掌握的语言及熟练度"><SimpleList values={resume.languages} placeholder="例如：英语（熟练）" emptyText="还没有添加语言" onChange={(values) => update('languages', values)} /></Section>
  </div>
}

function BulletEditor({ bullets, onChange }: { bullets: string[]; onChange: (bullets: string[]) => void }) {
  return <div className="bullet-editor"><div className="sub-label">工作内容 / 成果</div>{bullets.map((bullet, index) => <div className="bullet-row" key={index}><span>•</span><input value={bullet} placeholder="描述你的成果或负责内容" onChange={(event) => onChange(bullets.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button className="icon-button danger-icon" type="button" onClick={() => onChange(bullets.filter((_, itemIndex) => itemIndex !== index))} aria-label="删除要点" title="删除"><Trash2 size={14} /></button></div>)}<button className="inline-add" type="button" onClick={() => onChange([...bullets, ''])}><Plus size={14} />添加要点</button></div>
}

function SimpleList({ values, placeholder, emptyText, onChange }: { values: string[]; placeholder: string; emptyText: string; onChange: (values: string[]) => void }) {
  return <div className="simple-list">{values.length === 0 && <p className="empty-list">{emptyText}</p>}{values.map((value, index) => <div className="simple-list-row" key={index}><input value={value} placeholder={placeholder} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /><button className="icon-button" type="button" disabled={index === 0} onClick={() => onChange(moveAt(values, index, -1))} aria-label="上移条目" title="上移"><ChevronUp size={14} /></button><button className="icon-button" type="button" disabled={index === values.length - 1} onClick={() => onChange(moveAt(values, index, 1))} aria-label="下移条目" title="下移"><ChevronDown size={14} /></button><button className="icon-button danger-icon" type="button" onClick={() => onChange(values.filter((_, itemIndex) => itemIndex !== index))} aria-label="删除条目" title="删除"><Trash2 size={15} /></button></div>)}<button className="inline-add" type="button" onClick={() => onChange(addAt(values, values.length, ''))}><Plus size={14} />添加</button></div>
}
